 introTitle: 'hello dmm hahaha!',
    introDesc: `oánh nhau cả t k hả trịnh linhhh`,
    btnIntro: 'okkkkk',
    title: 'm bị ngu 😙',
    desc: 'mày bị thiểu năng kakakak ',
    btnYes: 'sao bt hay z <33',
    btnNo: 'Không,mày điên à :3',
    question:'chửi bố m đi ',
    btnReply: 'hộ cái ',
    mess: 't bị thiểu năng okkk',
    messDesc: 'ok t hiểu mà ',
    btnAccept: 'Oge <3',
}
